version: "1"
rules: # Array of rules
  - base: master # Required. Target branch
    upstream: porn-vault:master # Required. Must be in the same fork network.
    mergeMethod: rebase # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    assignees: # Optional
      - leadwolf
    reviewers: # Optional
      - leadwolf
    conflictReviewers: # Optional, on merge conflict assign a reviewer
      - leadwolf
  - base: dev
    upstream: porn-vault:dev # Required. Can be a branch in the same forked repo.
    mergeMethod: rebase # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    assignees: # Optional
      - leadwolf
    reviewers: # Optional
      - leadwolf
    conflictReviewers: # Optional, on merge conflict assign a reviewer
      - leadwolf
  - base: leadwolf-dev
    upstream: porn-vault:dev # Required. Can be a branch in the same forked repo.
    mergeMethod: rebase # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    conflictReviewers: # Optional, on merge conflict assign a reviewer
      - leadwolf
  - base: boi-dev
    upstream: porn-vault:dev # Required. Can be a branch in the same forked repo.
    mergeMethod: hardreset # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: true # Optional, merge pull request even when the mergeable_state is not clean. Default: false
    assignees: # Optional
      - leadwolf
    reviewers: # Optional
      - leadwolf
    conflictReviewers: # Optional, on merge conflict assign a reviewer
      - leadwolf
label: ":arrow_heading_down: pull" # Optional
